apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  REDIS_URL: "redis://redis-svc:6379"
  POSTGRES_URL: "postgresql://user:pass@postgres-svc:5432/ollivetrace"
  CLICKHOUSE_HOST: "clickhouse-svc"
  CLICKHOUSE_PORT: "8123"
  CLICKHOUSE_DB: "ollivetrace"
  INGEST_URL: "http://fastapi-ingest-svc:8000"
  NEXT_PUBLIC_INGEST_URL: "http://ollivetrace.local/api/metrics"
